name: surveyami
description: A Flutter starter template for creating new Project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  copy_with_extension: ^5.0.0
  dartz: ^0.10.1
  dio: any
  dio_log: ^2.0.3
  encrypt: ^5.0.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  form_builder_validators: ^8.4.0
  geolocator: ^9.0.2
  nested: ^1.0.0
  network_logger: ^1.0.3
  google_fonts: ^4.0.3
  talker_flutter: ^2.4.0
  talker_dio_logger: ^1.2.2
  easy_refresh: ^3.3.0+1
  get_it: ^7.2.0
  go_router_flow: ^6.0.0+3
  image_picker: ^0.8.6+1
  internet_connection_checker_plus: ^1.0.1
  path: any
  photo_view: ^0.14.0
  json_annotation: ^4.8.0
  logger: ^1.1.0
  shared_preferences: ^2.0.17
  sizer: ^2.0.15
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  change_app_package_name: ^1.1.0
  copy_with_extension_gen: ^5.0.0
  flutter_lints: ^2.0.1
  json_serializable: ^6.6.1

flutter:
  generate: true
  uses-material-design: true
