name: flutter_boilerplate
description: A Flutter starter template for creating new Project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  alice: ^0.3.2
  copy_with_extension: ^5.0.0
  dartz: ^0.10.1
  dio: ^4.0.6
  encrypt: ^5.0.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  form_builder_validators: ^8.4.0
  nested: ^1.0.0
  google_fonts: ^4.0.3
  easy_refresh: ^3.3.0+1
  get_it: ^7.2.0
  internet_connection_checker_plus: ^1.0.1
  json_annotation: ^4.8.0
  logger: ^1.1.0
  shared_preferences: ^2.0.17
  sizer: ^2.0.15
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  copy_with_extension_gen: ^5.0.0
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.1

flutter:
  generate: true
  uses-material-design: true
